export interface Artwork {
  title: string;
  medium: string;
  size: string;
  status: string;
  description: string;
  localPath: string;
  yearOrSeries: string;
}

export const artworks: Artwork[] = [
  { title: "Wild Goddess", medium: "Oil on canvas", size: "16×20", status: "Available", description: "Species: Sumatran Tiger (Panthera tigris sumatrae)", localPath: "/need-more-wildlife/gallery/wild-goddess.jpg", yearOrSeries: "2014" },
  { title: "Where They Belong", medium: "Oil on canvas", size: "16×20", status: "Available", description: "Species: Blue-headed Parrot (Pionus menstruus)", localPath: "/need-more-wildlife/gallery/where-they-belong.jpg", yearOrSeries: "2014" },
  { title: "High Water Everywhere", medium: "Oil on canvas", size: "20×24", status: "Available", description: "Species: Polar Bear (Ursus maritimus)", localPath: "/need-more-wildlife/gallery/high-water-everywhere.jpg", yearOrSeries: "2017" },
  { title: "What's the Buzz?", medium: "Oil on canvas", size: "24×36", status: "SOLD", description: "Species: Bumble Bee (Bombus sp.)", localPath: "/need-more-wildlife/gallery/what-s-the-buzz.jpg", yearOrSeries: "2017" },
  { title: "Vanishing Jewel", medium: "Oil on canvas", size: "24×24", status: "SOLD", description: "Species: Honduran Emerald (Amazilia luciae)", localPath: "/need-more-wildlife/gallery/vanishing-jewel.jpg", yearOrSeries: "2017" },
  { title: "Making Hay while the Sun Shines", medium: "Oil on canvas", size: "24×24", status: "Available", description: "Species: American Pika (Ochotona princeps)", localPath: "/need-more-wildlife/gallery/making-hay-while-the-sun-shines.jpg", yearOrSeries: "2017" },
  { title: "Going to Bat for Bananas", medium: "Oil on canvas", size: "24×24", status: "Available", description: "Species: Cave Nectar Bat (Eonycteris spelaea)", localPath: "/need-more-wildlife/gallery/going-to-bat-for-bananas.jpg", yearOrSeries: "2017" },
  { title: "Gimme Shelter", medium: "Oil on canvas", size: "24×36", status: "SOLD", description: "Species: Orangutan (Pongo pygmaeus)", localPath: "/need-more-wildlife/gallery/gimme-shelter.jpg", yearOrSeries: "2017" },
  { title: "House Burning Down", medium: "Oil on canvas", size: "24×24", status: "Available", description: "Species: American Pika (Ochotona princeps)", localPath: "/need-more-wildlife/gallery/house-burning-down.jpg", yearOrSeries: "2017" },
  { title: "Rust Never Sleeps", medium: "Oil on canvas", size: "24×24", status: "SOLD", description: "Species: Rusty Patched Bumble Bee (Bombus affinis)", localPath: "/need-more-wildlife/gallery/rust-never-sleeps.jpg", yearOrSeries: "2017" },
  { title: "Ten to One, Baby, One in Ten", medium: "Oil on canvas", size: "18×24", status: "SOLD", description: "Species: Monarch Butterfly (Danaus plexippus)", localPath: "/need-more-wildlife/gallery/ten-to-one-baby-one-in-ten.jpeg", yearOrSeries: "2017" },
  { title: "Little Cow, Little Calf Blues", medium: "Oil on canvas", size: "24×36", status: "Available", description: "Species: Vaquita (Phocoena sinus)", localPath: "/need-more-wildlife/gallery/little-cow-little-calf-blues.jpg", yearOrSeries: "2017" },
  { title: "Bee is for Blueberry", medium: "Oil on canvas", size: "20×24", status: "SOLD", description: "Species: Southeastern Blueberry Bee (Habropoda laboriosa)", localPath: "/need-more-wildlife/gallery/bee-is-for-blueberry.jpg", yearOrSeries: "2017" },
  { title: "Thorn Forest", medium: "Oil on canvas", size: "16×20", status: "Available", description: "Species: Prickly Pear (Opuntia ficus-indica)", localPath: "/need-more-wildlife/gallery/thorn-forest.jpg", yearOrSeries: "2017" },
  { title: "Ghost Visited by a Giant", medium: "Oil on canvas", size: "20×24", status: "Available", description: "Species: Ghost Orchid (Dendrophylax lindenii)", localPath: "/need-more-wildlife/gallery/ghost-visited-by-a-giant.jpg", yearOrSeries: "2017" },
  { title: "Losing Nemo", medium: "Oil on canvas", size: "20×20", status: "SOLD", description: "Species: Orange Clownfish (Amphiprion percula)", localPath: "/need-more-wildlife/gallery/losing-nemo.jpg", yearOrSeries: "2017" },
  { title: "Alpine Apparition", medium: "Oil on canvas", size: "24×36", status: "SOLD", description: "Species: Snow Leopard (Panthera uncia)", localPath: "/need-more-wildlife/gallery/alpine-apparition.jpg", yearOrSeries: "2017" },
  { title: "Born on the Bayou", medium: "Oil on canvas", size: "24×36", status: "Available", description: "Species: Mexican Free-Tailed Bat (Tadarida brasiliensis)", localPath: "/need-more-wildlife/gallery/born-on-the-bayou.jpg", yearOrSeries: "2017" },
  { title: "Possum up a Gum Tree", medium: "Oil on canvas", size: "20×24", status: "Available", description: "Species: White Lemuroid Ringtail Possum", localPath: "/need-more-wildlife/gallery/possum-up-a-gum-tree.jpg", yearOrSeries: "2017" },
  { title: "Pollinator in Repose", medium: "Oil on canvas", size: "20×24", status: "Available", description: "Species: Rufous Hummingbird (Selasphorus rufus)", localPath: "/need-more-wildlife/gallery/pollinator-in-repose.jpg", yearOrSeries: "2017" },
  { title: "Lost Treasure", medium: "Oil on canvas", size: "11×14", status: "Available", description: "Species: Panamanian Golden Frog (Atelopus zeteki)", localPath: "/need-more-wildlife/gallery/lost-treasure.jpg", yearOrSeries: "2017" },
  { title: "Possum up a Gum Tree Prototype", medium: "Pencil on drawing paper", size: "18×24", status: "Prototype", description: "Prototype drawing for the Possum up a Gum Tree painting", localPath: "/need-more-wildlife/gallery/possum-up-a-gum-tree-prototype.jpeg", yearOrSeries: "2017" },
  { title: "Seeing Ghosts in the Thicket Prototype", medium: "Pencil on drawing paper", size: "18×24", status: "Prototype", description: "Prototype drawing for Seeing Ghosts in the Thicket", localPath: "/need-more-wildlife/gallery/seeing-ghosts-in-the-thicket-prototype.jpeg", yearOrSeries: "2017" },
  { title: "Chimphood", medium: "Oil on canvas", size: "24×24", status: "Available", description: "Species: Common Chimpanzee (Pan troglodytes)", localPath: "/need-more-wildlife/gallery/chimphood.jpg", yearOrSeries: "2018" },
  { title: "High Water Everywhere Part II", medium: "Oil on canvas", size: "24×36", status: "SOLD", description: "Species: Polar Bear (Ursus maritimus)", localPath: "/need-more-wildlife/gallery/high-water-everywhere-part-ii.jpg", yearOrSeries: "2018" },
  { title: "Cotton Fields Back Home", medium: "Oil on canvas", size: "24×36", status: "Available", description: "Species: Monarch Butterfly (Danaus plexippus)", localPath: "/need-more-wildlife/gallery/cotton-fields-back-home.jpg", yearOrSeries: "2018" },
  { title: "A Skeleton of its Former Self", medium: "Oil on canvas", size: "24×36", status: "SOLD", description: "Species: Staghorn coral (Acropora cervicornis)", localPath: "/need-more-wildlife/gallery/a-skeleton-of-its-former-self.jpg", yearOrSeries: "2018" },
  { title: "Mother's Little Helper", medium: "Oil on canvas", size: "24×36", status: "Available", description: "Species: Chinese Pangolin (Manis pentadactyla)", localPath: "/need-more-wildlife/gallery/mother-s-little-helper.jpg", yearOrSeries: "2018" },
  { title: "Seeing Ghosts in the Thicket", medium: "Oil on canvas", size: "24×36", status: "Available", description: "Species: Ivory-Billed Woodpecker (Campephilus principalis)", localPath: "/need-more-wildlife/gallery/seeing-ghosts-in-the-thicket.jpg", yearOrSeries: "2018" },
  { title: "HAUNTED — HOUNDED — HUNTED", medium: "Acrylic on canvas", size: "8×10", status: "SOLD", description: "Species: Bioko putty-nosed monkey", localPath: "/need-more-wildlife/gallery/haunted-hounded-hunted.jpg", yearOrSeries: "2020" },
  { title: "El sueño perdido de un pangolin en las nubes", medium: "Acrylic on canvas", size: "8×10", status: "Available", description: "Species: Tree Pangolin (Manis tricuspis)", localPath: "/need-more-wildlife/gallery/el-sueno-perdido-de-un-pangolin-en-las-nubes-the-lost-dream-of-a-pangolin-in-the-clouds.jpeg", yearOrSeries: "2020" },
  { title: "Kala caminando por el bosque", medium: "Acrylic on canvas", size: "8×10", status: "Available", description: "Species: Tree Pangolin (Manis tricuspis)", localPath: "/need-more-wildlife/gallery/kala-caminando-por-el-bosque-saludando-una-mariposa-pangolin-walking-in-the-forest-greeted-by-a-butterfly.jpeg", yearOrSeries: "2020" },
  { title: "Kala de la noche", medium: "Acrylic on canvas", size: "8×10", status: "SOLD", description: "Species: Tree Pangolin (Manis tricuspis)", localPath: "/need-more-wildlife/gallery/kala-de-la-noche-pangolin-of-the-night.jpeg", yearOrSeries: "2020" },
  { title: "The End Approaches The Beginning", medium: "Acrylic on canvas", size: "8×10", status: "SOLD", description: "Species: Leatherback (Dermochelys coriacea)", localPath: "/need-more-wildlife/gallery/the-end-approaches-the-beginning.jpeg", yearOrSeries: "2020" },
  { title: "Chameleon in the field at Moca", medium: "Acrylic on canvas", size: "8×10", status: "SOLD", description: "Species: Chameleon (Chamaeleonidae)", localPath: "/need-more-wildlife/gallery/chameleon-in-the-field-at-moca.jpg", yearOrSeries: "2020" },
  { title: "Jumping for Joy Prototype", medium: "Pencil on drawing paper", size: "18×24", status: "Prototype", description: "Prototype drawing for Jumping for Joy commission", localPath: "/need-more-wildlife/gallery/jumping-for-joy-prototype.jpeg", yearOrSeries: "2019" },
  { title: "Jumping for Joy", medium: "Oil on canvas", size: "30×48", status: "SOLD", description: "Commission, 2019", localPath: "/need-more-wildlife/gallery/jumping-for-joy.jpg", yearOrSeries: "2019" },
  { title: "Happy Birthday Christelle!", medium: "Acrylic on canvas", size: "8×10", status: "SOLD", description: "Commission, 2020", localPath: "/need-more-wildlife/gallery/happy-birthday-christelle.jpg", yearOrSeries: "2020" },
  { title: "Rap, Rap, Rap", medium: "Acrylic on canvas", size: "8×10", status: "SOLD", description: "Species: African Grey Parrot (Psittacus erithacus)", localPath: "/need-more-wildlife/gallery/rap-rap-rap.jpeg", yearOrSeries: "2020" },
  { title: "Sweet Nectar", medium: "Acrylic on canvas", size: "8×10", status: "SOLD", description: "Species: Northern double-collared sunbird", localPath: "/need-more-wildlife/gallery/sweet-nectar.jpg", yearOrSeries: "2020" },
  { title: "Bubi Bells", medium: "Acrylic on wood", size: "", status: "SOLD", description: "Northern double-collared sunbird and map of Bioko Island", localPath: "/need-more-wildlife/gallery/bubi-bells.jpeg", yearOrSeries: "2020" },
  { title: "Bioko Mural", medium: "Mural", size: "", status: "Completed", description: "Mural at the Moca Wildlife Center, Bioko Island, Equatorial Guinea", localPath: "/need-more-wildlife/gallery/bioko-mural-at-moca-wildlife-center.jpeg", yearOrSeries: "2020" },
  { title: "Resolution", medium: "Oil on canvas", size: "24×24", status: "Available", description: "Secret Admirer Series", localPath: "/need-more-wildlife/gallery/resolution.jpeg", yearOrSeries: "Secret Admirer Series" },
  { title: "Sanctuary", medium: "Oil on canvas", size: "24×24", status: "Available", description: "Secret Admirer Series", localPath: "/need-more-wildlife/gallery/sanctuary.jpeg", yearOrSeries: "Secret Admirer Series" },
  { title: "Lioness Licking Leo Prototype", medium: "Pencil on drawing paper", size: "18×24", status: "Prototype", description: "Prototype drawing for the Secret Admirer Series", localPath: "/need-more-wildlife/gallery/lioness-licking-leo-prototype.jpeg", yearOrSeries: "Secret Admirer Series" },
];
